# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67bf87151d701909bf7a102add3d3ad56e3499f15bfbd2c9cf777e50da7dfb3000518d50bd0812f04bcc951246610bd4caed794e7801fb712bcc64aeeb8d9b8d

test:
  secret_key_base: 8e9a43a0972a24f4ef93f4e5dcc11619ea7098387139aa4c9272a1e71326f84ed982d69b533f7ebdaed3f639c7693195e81a0ef71be85a1ca12db624961fc4b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
